name: StrippedBroadcast
author: Fulminazzo
version: ${project.version}
description: StrippedBroadcast is an advanced recreation of the plugin RawMsg that adds more functionalities to the command.
api-version: 1.16
main: it.fulminazzo.sbc.StrippedBroadcast
softdepend: [LuckPerms, Vault]
commands:
  sbc:
    description: StrippedBroadcast main command
    permission: sbc.main
    aliases: [sbc, strippedbroadcast, sbroadcast, strippedbc]

permissions:
  sbc.main:
    description: Permission for /sbc