name: StrippedBroadcast
author: Fulminazzo
version: ${project.version}
description: A simple recration of the plugin RawMsg.
api-version: 1.16
main: it.fulminazzo.sbc.StrippedBroadcast
softdepend: [LuckPerms]
commands:
  sbc:
    description: StrippedBroadcast main command
    permission: sbc.main
    aliases: [sbc, strippedbroadcast, sbroadcast, strippedbc]

permissions:
  sbc.main:
    description: Permission for /sbc